// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantSystem.Infrastructure.Data;

#nullable disable

namespace RestaurantSystem.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260523111049_UpdateSeedData")]
    partial class UpdateSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RestaurantSystem.Domain.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("RestaurantSystem.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Klassiska stenugnsbakade pizzor",
                            Name = "Pizzor"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Färsk pasta med italienska råvaror",
                            Name = "Pasta"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Fräscha sallader med lokala råvaror",
                            Name = "Sallader"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Smått och gott att dela på",
                            Name = "Förrätter"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Grillade rätter från land och hav",
                            Name = "Kött & Fisk"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Söta avslutningar",
                            Name = "Efterrätter"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Kalla drycker och läsk",
                            Name = "Dryck"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Noggrant utvalda viner",
                            Name = "Viner"
                        });
                });

            modelBuilder.Entity("RestaurantSystem.Domain.Entities.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Tomatsås, mozzarella och färsk basilika",
                            IsAvailable = true,
                            Name = "Margherita",
                            Price = 115.00m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Tomatsås, mozzarella och parmaskinka",
                            IsAvailable = true,
                            Name = "Vesuvio",
                            Price = 135.00m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Tomatsås, mozzarella, skinka, champinjoner, oliver och kronärtskocka",
                            IsAvailable = true,
                            Name = "Quattro Stagioni",
                            Price = 145.00m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Tomatsås, mozzarella och salami piccante",
                            IsAvailable = true,
                            Name = "Diavola",
                            Price = 140.00m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Tryffelkräm, mozzarella, porcini och rucola",
                            IsAvailable = true,
                            Name = "Tartufo",
                            Price = 165.00m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Klassisk krämig sås med pancetta och pecorino",
                            IsAvailable = true,
                            Name = "Spaghetti Carbonara",
                            Price = 145.00m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "Långsamt kokt köttfärssås med parmesan",
                            IsAvailable = true,
                            Name = "Tagliatelle Bolognese",
                            Price = 150.00m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "Kryddig tomatsås med vitlök och chili",
                            IsAvailable = true,
                            Name = "Penne Arrabiata",
                            Price = 130.00m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Description = "Hemgjorda gnocchi med basilikopesto och körsbärstomater",
                            IsAvailable = true,
                            Name = "Gnocchi al Pesto",
                            Price = 155.00m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Description = "Romansallad, krutonger, parmesan och caesardressing",
                            IsAvailable = true,
                            Name = "Caesar Sallad",
                            Price = 115.00m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Description = "Buffelmozzarella, tomater, basilika och olivolja",
                            IsAvailable = true,
                            Name = "Caprese",
                            Price = 125.00m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Description = "Rucola, parmesanflagor, valnötter och balsamicodressing",
                            IsAvailable = true,
                            Name = "Rucola & Parmesan",
                            Price = 110.00m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            Description = "Rostat bröd med vitlökssmör och örter",
                            IsAvailable = true,
                            Name = "Vitlöksbröd",
                            Price = 55.00m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            Description = "Rostade brödschivor med tomater, vitlök och basilika",
                            IsAvailable = true,
                            Name = "Bruschetta",
                            Price = 65.00m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            Description = "Tunnskivad oxfilé med rucola, parmesan och tryffelolja",
                            IsAvailable = true,
                            Name = "Carpaccio",
                            Price = 145.00m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            Description = "Krämig burrata med rostade tomater och pesto",
                            IsAvailable = true,
                            Name = "Burrata",
                            Price = 135.00m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 5,
                            Description = "Grillad oxfilé med rucola, parmesan och tryffelolja",
                            IsAvailable = true,
                            Name = "Tagliata di Manzo",
                            Price = 285.00m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 5,
                            Description = "Ugnsbakad havsabborre med citron och kapris",
                            IsAvailable = true,
                            Name = "Branzino al Forno",
                            Price = 245.00m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 5,
                            Description = "Grillad kycklingbröst med rosmarin och citron",
                            IsAvailable = true,
                            Name = "Pollo alla Griglia",
                            Price = 195.00m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 5,
                            Description = "Vitlöksstekta räkor med chili och persilja",
                            IsAvailable = true,
                            Name = "Gamberi al Aglio",
                            Price = 225.00m
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 6,
                            Description = "Klassisk italiensk efterrätt med mascarpone",
                            IsAvailable = true,
                            Name = "Tiramisu",
                            Price = 85.00m
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 6,
                            Description = "Vaniljpannacotta med hallonsås",
                            IsAvailable = true,
                            Name = "Panna Cotta",
                            Price = 75.00m
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 6,
                            Description = "Tre kulor italiensk glass, välj smak",
                            IsAvailable = true,
                            Name = "Gelato",
                            Price = 65.00m
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 6,
                            Description = "Krispiga rör med ricottakräm och pistaschnötter",
                            IsAvailable = true,
                            Name = "Cannoli",
                            Price = 70.00m
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 7,
                            Description = "33cl",
                            IsAvailable = true,
                            Name = "Coca Cola",
                            Price = 35.00m
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 7,
                            Description = "Sparkling eller still, 33cl",
                            IsAvailable = true,
                            Name = "Mineralvatten",
                            Price = 30.00m
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 7,
                            Description = "Pressad apelsin- eller citronjuice",
                            IsAvailable = true,
                            Name = "Freshly Squeezed Juice",
                            Price = 55.00m
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 7,
                            Description = "Klassisk italiensk espresso",
                            IsAvailable = true,
                            Name = "Espresso",
                            Price = 35.00m
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 7,
                            Description = "Espresso med mjölkskum",
                            IsAvailable = true,
                            Name = "Cappuccino",
                            Price = 45.00m
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 8,
                            Description = "Toscansk rödvin, glas",
                            IsAvailable = true,
                            Name = "Chianti Classico",
                            Price = 95.00m
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 8,
                            Description = "Friskt vitt vin från Norditalien, glas",
                            IsAvailable = true,
                            Name = "Pinot Grigio",
                            Price = 85.00m
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 8,
                            Description = "Italienskt mousserande vin, glas",
                            IsAvailable = true,
                            Name = "Prosecco",
                            Price = 90.00m
                        });
                });

            modelBuilder.Entity("RestaurantSystem.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RestaurantSystem.Domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("RestaurantSystem.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("RestaurantSystem.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantSystem.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("RestaurantSystem.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RestaurantSystem.Domain.Entities.MenuItem", b =>
                {
                    b.HasOne("RestaurantSystem.Domain.Entities.Category", "Category")
                        .WithMany("MenuItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RestaurantSystem.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("RestaurantSystem.Domain.Entities.MenuItem", "MenuItem")
                        .WithMany("OrderItems")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantSystem.Domain.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RestaurantSystem.Domain.Entities.Category", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("RestaurantSystem.Domain.Entities.MenuItem", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("RestaurantSystem.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
